export const phrases = {
    short: [
      "The coffee machine hummed quietly in the corner as morning sunlight filtered through the kitchen window.",
  "She grabbed her keys and rushed out the door, hoping to catch the last train home.",
  "The old bookstore held countless stories within its weathered walls and creaking wooden shelves.",
  "Children's laughter echoed across the playground as clouds drifted lazily overhead.",
  "The cat stretched lazily on the windowsill, watching birds flutter past in the garden.",
  "Fresh snow blanketed the city streets, turning the urban landscape into a winter wonderland.",
  "He typed furiously at his keyboard, racing against time to meet the deadline.",
  "The aroma of freshly baked bread wafted through the neighborhood early Sunday morning.",
  "Waves crashed rhythmically against the shore as seagulls circled overhead, searching for their next meal.",
  "The museum's ancient artifacts told silent stories of civilizations long past.",
  "Stars twinkled brightly in the clear night sky, creating nature's own light show.",
  "The garden burst with color as spring flowers began their annual display.",
  "A gentle breeze rustled through the trees, carrying the sweet scent of blooming jasmine.",
  "The artist's brush danced across the canvas, bringing imagination to life with each stroke.",
  "Rain tapped gently against the windows while thunder rumbled in the distance."
    ],
    medium: [
      "The local farmers' market bustled with activity as vendors arranged their fresh produce and handcrafted goods, while early morning shoppers carefully selected the best ingredients for their weekend meals.",
  "In the cozy coffee shop downtown, students huddled over laptops and textbooks, sipping steaming drinks while soft jazz music played in the background, creating the perfect study atmosphere.",
  "The hiking trail wound its way through ancient pine forests, crossing bubbling streams and revealing breathtaking valley views that made every challenging step worthwhile for the adventurous trekkers.",
  "As the sun set over the city skyline, office workers began their evening commute home, while street musicians filled the cooling air with melodies that echoed between tall buildings.",
  "The small town's annual festival brought together locals and visitors alike, filling the main street with the sounds of live music, the smell of street food, and the joy of community.",
  "Inside the busy restaurant kitchen, chefs moved with practiced precision, transforming raw ingredients into culinary masterpieces while servers orchestrated a complex dance of service.",
  "The old grandfather clock in the hallway marked time with steady precision, its gentle ticking a reminder of countless moments shared within these familiar walls.",
  "During the summer evening, fireflies danced through the garden like tiny lanterns, while crickets provided their nightly symphony and a gentle breeze carried the scent of jasmine.",
  "The antique bookshop's shelves held countless stories waiting to be discovered, their leather-bound spines and yellowed pages promising adventures to those who dared explore them.",
  "As rain fell steadily outside, the library remained a haven of quiet concentration, with readers lost in their chosen worlds while others browsed shelves for their next literary escape.",
  "The art gallery opening attracted a diverse crowd of enthusiasts and critics, each person finding their own meaning in the colorful canvases that adorned the pristine walls.",
  "Morning fog rolled through the valley, gradually revealing the landscape as the sun rose higher, while early risers began their daily routines in the peaceful countryside setting.",
  "The botanical garden showcased nature's diversity in carefully curated displays, from delicate orchids to towering palms, each plant telling its own story of adaptation and survival.",
  "Professional dancers moved gracefully across the studio floor, their reflections multiplied in wall-length mirrors as they prepared for the upcoming performance with determined concentration.",
  "The weekend market square transformed into a vibrant tapestry of colors and cultures, with international food stalls and local artisans sharing their traditions with curious visitors."
    ],
    long: [
      "The old library, with its towering shelves filled with dusty tomes and ancient manuscripts, seemed to hold the secrets of centuries past, whispering stories of forgotten worlds and long-lost civilizations to those who dared to listen closely in the silence.",
    "As the storm clouds gathered on the horizon, the once-calm sea began to churn violently, its waves rising like giants ready to clash, while the fishermen hurried to secure their boats, hoping to outlast nature's fury.",
    "The bustling marketplace was a kaleidoscope of colors, sounds, and smells, with vendors calling out to passersby, offering everything from fresh produce to handmade crafts, creating a vibrant tapestry of life and commerce.",
    "High in the mountains, where the air was thin and the snow never melted, the climbers pressed on, their determination unwavering despite the biting cold and the treacherous terrain that tested their limits at every step.",
    "The orchestra's music swelled, filling the grand concert hall with a symphony of emotions, each note telling a story of love, loss, and triumph, as the audience sat in rapt silence, completely captivated by the performance.",
    "In the quiet hours of the night, when the world seemed to stand still, the writer sat by the dim light of a desk lamp, pouring their thoughts onto paper, crafting a story that would one day inspire countless others.",
    "The ancient ruins, hidden deep within the jungle, stood as a silent reminder of a once-great civilization, their stone walls covered in intricate carvings that told the tales of gods, warriors, and kings long forgotten by time.",
    "As the train rattled along the tracks, the passengers gazed out at the passing landscape, each lost in their own thoughts, while the rhythmic clatter of the wheels created a soothing backdrop to their journeys.",
    "The chef worked tirelessly in the kitchen, their hands moving with precision and grace as they transformed simple ingredients into a masterpiece of flavors, each dish a reflection of their passion and creativity.",
    "The city skyline, illuminated by the golden hues of the setting sun, stood as a testament to human ingenuity and ambition, its towering skyscrapers reaching for the heavens like modern-day monuments to progress.",
    "In the depths of space, where stars burned brightly against the infinite darkness, the spacecraft drifted silently, its crew marveling at the beauty and vastness of the universe that stretched out before them.",
    "The festival was a riot of colors and sounds, with dancers moving to the rhythm of traditional drums, their vibrant costumes swirling like living art, while the aroma of street food filled the air, tempting everyone who passed by.",
    "The detective carefully examined the clues scattered across the crime scene, piecing together the puzzle with a sharp mind and unwavering focus, determined to uncover the truth hidden beneath layers of deception.",
    "The garden, a sanctuary of peace and beauty, was alive with the hum of bees and the fragrance of blooming flowers, each plant carefully tended to by the gardener, who saw their work as a labor of love.",
    "As the first rays of dawn broke over the horizon, the world slowly awakened, the sky painted in shades of pink and orange, while the birds began their morning chorus, heralding the start of a new day full of possibilities.",
    "The local farmers' market bustled with activity as vendors arranged their fresh produce and handcrafted goods, while early morning shoppers carefully selected the best ingredients for their weekend meals.",
    ]
  };

  export const textOptions = [
    "The quick brown fox jumps over the lazy dog. Programming is the art of telling another human what one wants the computer to do.",
    "In the world of coding, every semicolon matters. A single character can make the difference between a working program and a syntax error that keeps you debugging for hours.",
    "Technology has revolutionized the way we live, work, and connect with others. As we continue to innovate, the possibilities seem endless in this digital age.",
    "Software development is like building a house. You need a solid foundation, careful planning, and attention to detail. Testing ensures your structure won't collapse.",
    "The best code is not just functional but also readable and maintainable. Clean code reads like well-written prose and tells a story about its purpose.",
    "Artificial intelligence and machine learning are transforming industries across the globe. The future holds endless possibilities for those who embrace these technologies.",
    "Great developers write code that humans can understand. Documentation is not just helpful; it's essential for maintaining and scaling software projects effectively.",
    "Version control is like a time machine for your code. Git allows developers to experiment freely, knowing they can always return to a working state if needed.",
    "The internet is a vast network connecting billions of devices worldwide. Every click, every search, and every message travels through this intricate web of connections.",
    "Security in software development is not an afterthought but a fundamental requirement. Every line of code must be written with potential vulnerabilities in mind."
  ];